# Generated by Django 5.2.6 on 2025-12-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="posters/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("palette", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="scenes/")),
                ("movie_title", models.CharField(max_length=200)),
                (
                    "positivity_level",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                        ]
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "avg_s",
                    models.FloatField(
                        blank=True, help_text="Average Saturation", null=True
                    ),
                ),
                (
                    "avg_v",
                    models.FloatField(blank=True, help_text="Average Value", null=True),
                ),
                (
                    "dom_h",
                    models.IntegerField(
                        blank=True, help_text="Dominant Hue (0-359)", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["positivity_level"], name="app_scene_positiv_171fb8_idx"
                    ),
                    models.Index(
                        fields=["movie_title"], name="app_scene_movie_t_9d224a_idx"
                    ),
                ],
            },
        ),
    ]
